name: Weekly NIST SP 800 Updates
on:
  schedule:
    - cron: "0 14 * * 1"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run and open PR
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO:    ${{ secrets.GITHUB_REPO }}
        run: |
          python -m app.main --topk 10
